# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61cc1badf5d9afb7ce28f53b97495a8c5e97632260b54341f8b1f5fd9f66137eaa165ad115a08f20020e1bdfd8084d9ca026e856834f24a723bcb7f43e1283eb

test:
  secret_key_base: 6f9d47dccf2b064b3be58c7e02693f95a4aead657bb68b7b48b0449eda299cd747a42524b54bd3ef3fdf6f720e13cef6a3b3481fd1f3bb88b61c79f1f468fde4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
